name: plotcheck
channels:
  - conda-forge
 dependencies:
   # Recommended that xarray is version 2023.7.0 or later
   - xarray
   - pandas
   - numpy
   - glob
   - os
   - time
   - matplotlib
   - sys
   - argparse
   - tabulate
   - cartopy.crs
