name: plotcheck
channels:
  - conda-forge
dependencies:
  # Recommended that xarray is version 2023.7.0 or later
  # (to avoid issues with reading datasets)
  - python=3.11.*
  - pip
  - pip:
    - os
    - sys
    - PIL
    - glob
    - time
    - FPDF
    - numpy
    - xarray
    - pandas
    - cftime
    - cartopy
    - datetime
    - argparse
    - tabulate
    - matplotlib
